"""initial migration

Revision ID: aa7f45b9c939
Revises: 
Create Date: 2024-11-23 14:27:57.272128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa7f45b9c939'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('batches',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'batch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('batch_name', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('sales_price', sa.Float(), nullable=False),
                    sa.Column('warehouse', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_batches_batch_number'),
                    'batches', ['batch_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batches_batch_number'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('products')
    # ### end Alembic commands ###
